version: '3.1'
volumes:
   geoserver-data:
   settings:
services:
  deymzar-geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - settings:/settings
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - RECREATE_DATADIR=${RECREATE_DATADIR}
      - HTTP_PROXY_NAME
      - HTTP_PROXY_PORT
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
      - GEOSERVER_UID=1000
      - GEOSERVER_GID=1000
      - USER=vagrant
      - GROUP_NAME=vagrant
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
