$schema: "http://json-schema.org/draft-07/schema#"
title: RepoConfig
description: Configuration for Gemini Code Assist

have_fun: false
ignore_patterns:
  - "**/resources/**"
  - "**/docs/**"
  - "**/README.md"
  - "**/.github/ISSUE_TEMPLATE/**"
  - "**/.git/**"

memory_config:
  disabled: false

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true