name: weekly-image-updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'



jobs:
  update-geoserver-image-weekly:

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check latest GeoServer version
        id: geoserver_check
        shell: bash
        run: |
          IMAGE_VERSION=3.12-slim
          docker run --rm \
            -v "$PWD/.github/workflows/scripts:/scripts" \
            -v "$GITHUB_OUTPUT:/github_output/github_output.txt" \
            python:${IMAGE_VERSION} \
            sh /scripts/check_geoserver_version.sh

      - name: Check latest Tomcat version
        id: tomcat_check
        shell: bash
        run: |
          IMAGE_VERSION=3.12-slim
          docker run --rm \
            -v "$PWD/.github/workflows/scripts:/scripts" \
            -v "$GITHUB_OUTPUT:/github_output/github_output.txt" \
            python:${IMAGE_VERSION} \
            sh /scripts/check_tomcat_version.sh

      
    

      - name: Read published image metadata
        id: published_image
        shell: bash
        run: |
          set -euo pipefail

          docker pull kartoza/geoserver:latest
          CONTAINER_ID=$(docker create kartoza/geoserver:latest)

          docker cp "${CONTAINER_ID}:/etc/kartoza/build_info.env" ./build_info.env

          docker rm "${CONTAINER_ID}"

          VERSION_INFO=$(cat ./build_info.env)

          echo "$VERSION_INFO"

          TOMCAT_VERSION=$(echo "$VERSION_INFO" | grep '^TOMCAT_VERSION=' | cut -d= -f2)
          TOMCAT_VERSION_DIGEST=$(echo "$VERSION_INFO" | grep '^TOMCAT_DIGEST_SHA=' | cut -d= -f2)
          GEOSERVER_VERSION=$(echo "$VERSION_INFO" | grep '^GEOSERVER_VERSION=' | cut -d= -f2)

          echo "TOMCAT_VERSION=$TOMCAT_VERSION" >> "$GITHUB_OUTPUT"
          echo "TOMCAT_VERSION_DIGEST=$TOMCAT_VERSION_DIGEST" >> "$GITHUB_OUTPUT"
          echo "GEOSERVER_VERSION=$GEOSERVER_VERSION" >> "$GITHUB_OUTPUT"
          

      - name: Published Tomcat Digest
        id: tomcat_digest_comparison
        shell: bash
        run: |
          PUBLISHED_TOMCAT="${{ steps.published_image.outputs.TOMCAT_VERSION }}"
          docker pull tomcat:${PUBLISHED_TOMCAT}
          TOMCAT_DIGEST=$(docker inspect \
            --format='{{index .RepoDigests 0}}' \
            tomcat:${PUBLISHED_TOMCAT})
          echo "${TOMCAT_DIGEST}"
          echo "tomcat_sha=${TOMCAT_DIGEST}" >> $GITHUB_OUTPUT
          

      - name: Determine if rebuild is needed
        id: rebuild_check
        shell: bash
        run: |
          set -euo pipefail

          NEEDS_BUILD=false

          LATEST_GEOSERVER="${{ steps.geoserver_check.outputs.major }}.${{ steps.geoserver_check.outputs.minor }}.${{ steps.geoserver_check.outputs.bugfix }}"
          PUBLISHED_GEOSERVER="${{ steps.published_image.outputs.GEOSERVER_VERSION }}"

          LATEST_TOMCAT="${{ steps.tomcat_check.outputs.tomcat_version }}"
          PUBLISHED_TOMCAT="${{ steps.published_image.outputs.TOMCAT_VERSION }}"
          
          PUBLISHED_TOMCAT_DIGEST="${{ steps.published_image.outputs.TOMCAT_VERSION_DIGEST }}"
          DOCKERHUB_TOMCAT_DIGEST="${{ steps.tomcat_digest_comparison.outputs.tomcat_sha }}"
          

          echo "Published GeoServer: $PUBLISHED_GEOSERVER"
          echo "Latest GeoServer:    $LATEST_GEOSERVER"

          echo "Published Tomcat:    $PUBLISHED_TOMCAT"
          echo "Latest Tomcat:       $LATEST_TOMCAT"
          
          echo "Latest Tomcat Digest:       $DOCKERHUB_TOMCAT_DIGEST"
          echo "Published Tomcat Digest:    $PUBLISHED_TOMCAT_DIGEST"
          

          if [ "$PUBLISHED_GEOSERVER" != "$LATEST_GEOSERVER" ]; then
            echo "GeoServer version changed"
            NEEDS_BUILD=true
          fi

          if [ "$PUBLISHED_TOMCAT" != "$LATEST_TOMCAT" ]; then
            echo "Tomcat version changed"
            NEEDS_BUILD=true
          fi
          
          if [ "$PUBLISHED_TOMCAT_DIGEST" != "$DOCKERHUB_TOMCAT_DIGEST" ]; then
            echo "Tomcat version changed"
            NEEDS_BUILD=true
          fi

          echo "needs_build=$NEEDS_BUILD" >> "$GITHUB_OUTPUT"

      - name: Trigger build-latest workflow
        if: steps.rebuild_check.outputs.needs_build == 'true'
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-image.yaml',
              ref: 'develop'
            })
